return {
 ["htmlfiles"]={ "QuestWorlds-div.html" },
 ["htmlroot"]="QuestWorlds-div.html",
 ["identifier"]="1f11c1f0-4701-98b9-996b-0e8d87b693f1",
 ["imagefile"]="styles/QuestWorlds-images.css",
 ["imagepath"]="images",
 ["images"]={
  ["image>1"]={
   ["element"]="image",
   ["height"]="2.540cm",
   ["id"]="image-1",
   ["name"]="Logos/QW-Stamp-Red.png",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/QW-Stamp-Red.png",
   ["used"]="../../Logos/QW-Stamp-Red.png",
   ["width"]="2.540cm",
  },
  ["image>2"]={
   ["element"]="image",
   ["height"]="2.540cm",
   ["id"]="image-2",
   ["name"]="Logos/QW-Stamp-Black.png",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/QW-Stamp-Black.png",
   ["used"]="../../Logos/QW-Stamp-Black.png",
   ["width"]="2.540cm",
  },
 },
 ["language"]="en",
 ["metadata"]={},
 ["name"]="QuestWorlds",
 ["stylepath"]="styles",
 ["styles"]={ "QuestWorlds-defaults.css", "QuestWorlds-images.css", "QuestWorlds-styles.css" },
 ["xhtmlfiles"]={ "QuestWorlds-tag.xhtml" },
 ["xmlfiles"]={ "QuestWorlds-raw.xml" },
}